<a href="https://colab.research.google.com/github/Rohanrathod7/my-ml-labs/blob/main/20_Introduction_to_Deep_Learning_with_PyTorch/01_Introduction_to_PyTorch%2C_a_Deep_Learning_Library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 4. TF-IDF and similarity scores


learn how to compute tf-idf weights and the cosine similarity score between two vectors. You will use these concepts to build a movie and a TED Talk recommender. Finally, you will also learn about word embeddings and using word vector representations, you will compute similarities between various Pink Floyd songs.

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
import datetime as dt
# Import confusion matrix and train_test_split
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split, KFold, cross_val_score, GridSearchCV
from sklearn.linear_model import Ridge, Lasso, LogisticRegression, LinearRegression
from scipy.cluster.hierarchy import linkage, dendrogram
import matplotlib.pyplot as plt
from sklearn.linear_model import SGDClassifier

url = "https://raw.githubusercontent.com/Rohanrathod7/my-ml-labs/main/19_Feature_Engineering_for_NLP_in_Python/Dataset/ted.csv"
# Read the CSV file
# Apply pd.to_numeric only to relevant columns, excluding 'text'
ted = pd.read_csv(url)


display(ted.head())

transcript  \
0  We're going to talk — my — a new lecture, just...   
1  This is a representation of your brain, and yo...   
2  It's a great honor today to share with you The...   
3  My passions are music, technology and making t...   
4  It used to be that if you wanted to get a comp...   

                                                 url  
0  https://www.ted.com/talks/al_seckel_says_our_b...  
1  https://www.ted.com/talks/aaron_o_connell_maki...  
2  https://www.ted.com/talks/carter_emmart_demos_...  
3  https://www.ted.com/talks/jared_ficklin_new_wa...  
4  https://www.ted.com/talks/jeremy_howard_the_wo...

In [ ]:
!python3 pip install spacy
!python3 -m spacy download en_core_web_sm

python3: can't open file '/content/pip': [Errno 2] No such file or directory
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 94.2 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [ ]:
# Load en_core_web_sm and create an nlp object
import spacy
nlp = spacy.load("en_core_web_sm")

**tf-idf weight of commonly occurring words**  
The word bottle occurs 5 times in a particular document D and also occurs in every document of the corpus. What is the tf-idf weight of bottle in D?

    -> 0

    In fact, the tf-idf weight for bottle in every document will be 0. This is because the inverse document frequency is constant across documents in a corpus and since bottle occurs in every document, its value is log(1), which is 0.

**tf-idf vectors for TED talks**  
In this exercise, you have been given a corpus ted which contains the transcripts of 500 TED Talks. Your task is to generate the tf-idf vectors for these talks.

In a later lesson, we will use these vectors to generate recommendations of similar talks based on the transcript.

In [ ]:
# Import TfidfVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

# Create TfidfVectorizer object
vectorizer = TfidfVectorizer()

# Generate matrix of word vectors
tfidf_matrix = vectorizer.fit_transform(ted)

# Print the shape of tfidf_matrix
print(tfidf_matrix.shape)

#  You now know how to generate tf-idf vectors for a given corpus of text.
#  You can use these vectors to perform predictive modeling just like we did with CountVectorizer.
#   In the next few lessons, we will see another extremely useful application of the vectorized form of documents: generating recommendations.

(2, 2)


### Cosine similarity

**Range of cosine scores**  
Which of the following is a possible cosine score for a pair of document vectors?

    -> 0.84

    Since document vectors use only non-negative weights, the cosine score lies between 0 and 1.

**Computing dot product**  
In this exercise, we will learn to compute the dot product between two vectors, A = (1, 3) and B = (-2, 2), using the numpy library. More specifically, we will use the np.dot() function to compute the dot product of two numpy arrays.

In [ ]:
# Initialize numpy vectors
A = np.array([1,3])
B = np.array([-2,2])

# Compute dot product
dot_prod = np.dot(A, B)

# Print dot product
print(dot_prod)

# The dot product of the two vectors is 1 * -2 + 3 * 2 = 4, which is indeed the output produced.
# We will not be using np.dot() too much in this course but it can prove to be a helpful function
# while computing dot products between two standalone vectors.

4


***Cosine similarity matrix of a corpus***  
In this exercise, you have been given a corpus, which is a list containing five sentences. The corpus is printed in the console. You have to compute the cosine similarity matrix which contains the pairwise cosine similarity score for every pair of sentences (vectorized using tf-idf).

Remember, the value corresponding to the ith row and jth column of a similarity matrix denotes the similarity score for the ith and jth vector.

In [ ]:
# Import cosine_similarity
from sklearn.metrics.pairwise import cosine_similarity
# Initialize an instance of tf-idf Vectorizer
tfidf_vectorizer = TfidfVectorizer()

# Import CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer

url = "https://raw.githubusercontent.com/Rohanrathod7/my-ml-labs/main/19_Feature_Engineering_for_NLP_in_Python/Dataset/movie_overviews.csv"
# Read the CSV file
corpus = ['The sun is the largest celestial body in the solar system', 'The solar system consists of the sun and eight revolving planets', 'Ra was the Egyptian Sun God', 'The Pyramids were the pinnacle of Egyptian architecture', 'The quick brown fox jumps over the lazy dog']



# Fill missing values in 'tagline' with empty strings



# Generate the tf-idf vectors for the corpus
tfidf_matrix = tfidf_vectorizer.fit_transform(corpus)

# Compute and print the cosine similarity matrix
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)
print(cosine_sim)

# As you will see in a subsequent lesson, computing the cosine similarity matrix lies at the heart of many practical systems such as recommenders.
# From our similarity matrix, we see that the first and the second sentence are the most similar.
# Also the fifth sentence has, on average, the lowest pairwise cosine scores.
# This is intuitive as it contains entities that are not present in the other sentences.

[[1.         0.36413198 0.18314713 0.18435251 0.16336438]
 [0.36413198 1.         0.15054075 0.21704584 0.11203887]
 [0.18314713 0.15054075 1.         0.21318602 0.07763512]
 [0.18435251 0.21704584 0.21318602 1.         0.12960089]
 [0.16336438 0.11203887 0.07763512 0.12960089 1.        ]]


### Building a plot line based recommender

**Comparing linear_kernel and cosine_similarity**  
In this exercise, you have been given tfidf_matrix which contains the tf-idf vectors of a thousand documents. Your task is to generate the cosine similarity matrix for these vectors first using cosine_similarity and then, using linear_kernel.

We will then compare the computation times for both functions.

***Compute the cosine similarity matrix for tfidf_matrix using cosine_similarity.***

In [ ]:
import time

# Record start time
start = time.time()

# Compute cosine similarity matrix
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

# Print cosine similarity matrix
print(cosine_sim)

# Print time taken
print("Time taken: %s seconds" %(time.time() - start))

[[1.         0.36413198 0.18314713 0.18435251 0.16336438]
 [0.36413198 1.         0.15054075 0.21704584 0.11203887]
 [0.18314713 0.15054075 1.         0.21318602 0.07763512]
 [0.18435251 0.21704584 0.21318602 1.         0.12960089]
 [0.16336438 0.11203887 0.07763512 0.12960089 1.        ]]
Time taken: 0.0061833858489990234 seconds


In [ ]:
import time
from sklearn.metrics.pairwise import linear_kernel

# Record start time
start = time.time()

# Compute cosine similarity matrix
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

# Print cosine similarity matrix
print(cosine_sim)

# Print time taken
print("Time taken: %s seconds" %(time.time() - start))

# Notice how both linear_kernel and cosine_similarity produced the same result.
# However, linear_kernel took a smaller amount of time to execute.
# When you're working with a very large amount of data and your vectors are in the tf-idf representation,
# it is good practice to default to linear_kernel to improve performance.
#  (NOTE: In case, you see linear_kernel taking more time, it's because the dataset we're dealing with is
#   extremely small and Python's time module is incapable of capture such minute time differences accurately)

[[1.         0.36413198 0.18314713 0.18435251 0.16336438]
 [0.36413198 1.         0.15054075 0.21704584 0.11203887]
 [0.18314713 0.15054075 1.         0.21318602 0.07763512]
 [0.18435251 0.21704584 0.21318602 1.         0.12960089]
 [0.16336438 0.11203887 0.07763512 0.12960089 1.        ]]
Time taken: 0.0013508796691894531 seconds


**Plot recommendation engine**  
In this exercise, we will build a recommendation engine that suggests movies based on similarity of plot lines. You have been given a get_recommendations() function that takes in the title of a movie, a similarity matrix and an indices series as its arguments and outputs a list of most similar movies. indices has already been provided to you.

You have also been given a movie_plots Series that contains the plot lines of several movies. Your task is to generate a cosine similarity matrix for the tf-idf vectors of these plots.

Consequently, we will check the potency of our engine by generating recommendations for one of my favorite movies, The Dark Knight Rises.

In [ ]:
# Initialize the TfidfVectorizer
tfidf = TfidfVectorizer(stop_words='english')

url = "https://raw.githubusercontent.com/Rohanrathod7/my-ml-labs/main/19_Feature_Engineering_for_NLP_in_Python/Dataset/movie_overviews.csv"
# Read the CSV file
movie_plots = pd.read_csv(url)

# Fill missing values in 'overview' with empty strings
movie_plots['overview'] = movie_plots['overview'].fillna('')

display(movie_plots.head())

# Construct the TF-IDF matrix
tfidf_matrix = tfidf.fit_transform(movie_plots["overview"])

# Generate the cosine similarity matrix
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

# Placeholder for indices - replace with your actual indices Series
indices = pd.Series(movie_plots.index, index=movie_plots['title']).drop_duplicates()

# Placeholder for get_recommendations function - replace with your actual function
def get_recommendations(title, cosine_sim, indices):
    # Get the index of the movie that matches the title
    idx = indices[title]
    # Get the pairwsie similarity scores
    sim_scores = list(enumerate(cosine_sim[idx]))
    # Sort the movies based on the similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    # Get the scores for 10 most similar movies
    sim_scores = sim_scores[1:11]
    # Get the movie indices
    movie_indices = [i[0] for i in sim_scores]
    # Return the top 10 most similar movies
    return movie_plots['title'].iloc[movie_indices]

# Generate recommendations
print(get_recommendations('The Dark Knight Rises', cosine_sim, indices))

# You've just built your very first recommendation system. Notice how the recommender correctly identifies
# 'The Dark Knight Rises' as a Batman movie and recommends other Batman movies as a result. This sytem is,
# of course, very primitive and there are a host of ways in which it could be improved. One method would be
# to look at the cast, crew and genre in addition to the plot to generate recommendations. We will not be covering this
# in this course but you have all the tools necessary to accomplish this. Do give it a try!

id                        title  \
0    862                    Toy Story   
1   8844                      Jumanji   
2  15602             Grumpier Old Men   
3  31357            Waiting to Exhale   
4  11862  Father of the Bride Part II   

                                            overview  \
0  Led by Woody, Andy's toys live happily in his ...   
1  When siblings Judy and Peter discover an encha...   
2  A family wedding reignites the ancient feud be...   
3  Cheated on, mistreated and stepped on, the wom...   
4  Just when George Banks has recovered from his ...   

                                             tagline  
0                                                NaN  
1          Roll the dice and unleash the excitement!  
2  Still Yelling. Still Fighting. Still Ready for...  
3  Friends are the people who let you be yourself...  
4  Just When His World Is Back To Normal... He's ...

132                              Batman Forever
6907                            The Dark Knight
1116                             Batman Returns
7573                 Batman: Under the Red Hood
524                                      Batman
7907                           Batman: Year One
8171    Batman: The Dark Knight Returns, Part 1
2581               Batman: Mask of the Phantasm
8232    Batman: The Dark Knight Returns, Part 2
6150                              Batman Begins
Name: title, dtype: object


**The recommender function**  
In this exercise, we will build a recommender function get_recommendations(), as discussed in the lesson and the previous exercise. As we know, it takes in a title, a cosine similarity matrix, and a movie title and index mapping as arguments and outputs a list of 10 titles most similar to the original title (excluding the title itself).

You have been given a dataset metadata that consists of the movie titles and overviews. The head of this dataset has been printed to console.

In [ ]:
# Generate mapping between titles and index
indices = pd.Series(movie_plots.index, index=movie_plots['title']).drop_duplicates()

def get_recommendations(title, cosine_sim, indices):
    # To get the index of the movie that matches the title
    idx = indices[title]
    # Sort the movies based on the similarity scores
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    # Get the scores for 10 most similar movies
    sim_scores = sim_scores[1:11]
    # Get the movie indices
    movie_indices = [i[0] for i in sim_scores]
    # Return the top 10 most similar movies
    return movie_plots['title'].iloc[movie_indices]

    # With this recommender function in our toolkit, we are now in a very good place to build the rest of the components of our recommendation engine.

**TED talk recommender**  
In this exercise, we will build a recommendation system that suggests TED Talks based on their transcripts. You have been given a get_recommendations() function that takes in the title of a talk, a similarity matrix and an indices series as its arguments, and outputs a list of most similar talks. indices has already been provided to you.

You have also been given a transcripts series that contains the transcripts of around 500 TED talks. Your task is to generate a cosine similarity matrix for the tf-idf vectors of the talk transcripts.

In [ ]:
url = "https://raw.githubusercontent.com/Rohanrathod7/my-ml-labs/main/19_Feature_Engineering_for_NLP_in_Python/Dataset/ted.csv"
# Read the CSV file
ted = pd.read_csv(url)

display(ted.head())

# Initialize the TfidfVectorizer
tfidf = TfidfVectorizer(stop_words='english')

# Construct the TF-IDF matrix
tfidf_matrix = tfidf.fit_transform(ted["transcript"])

# Generate the cosine similarity matrix
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

# Generate mapping between URLs and index
indices = pd.Series(ted.index, index=ted['url']).drop_duplicates()

def get_recommendations(talk_url, cosine_sim, indices):
    # Get the index of the talk that matches the URL
    try:
        idx = indices[talk_url]
    except KeyError:
        return f"Talk with URL '{talk_url}' not found in the dataset indices."

    # Get the pairwise similarity scores
    sim_scores = list(enumerate(cosine_sim[idx]))
    # Sort the talks based on the similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    # Get the scores for 10 most similar talks (excluding the talk itself)
    sim_scores = sim_scores[1:11]
    # Get the talk indices
    talk_indices = [i[0] for i in sim_scores]
    # Return the URLs of the top 10 most similar talks
    return ted['url'].iloc[talk_indices]


# Generate recommendations for the first talk in the dataset as an example
example_talk_url = ted['url'].iloc[0]
print(f"Recommendations for talk at URL: {example_talk_url}")
print(get_recommendations(example_talk_url, cosine_sim, indices))

# If you want recommendations for a specific talk like '5 ways to kill your dreams', you would need its corresponding URL from the dataset.
# For example, if the URL for '5 ways to kill your dreams' is 'https://www.ted.com/talks/xyz_5_ways_to_kill_your_dreams', you would call:
# print(get_recommendations('https://www.ted.com/talks/xyz_5_ways_to_kill_your_dreams', cosine_sim, indices))

transcript  \
0  We're going to talk — my — a new lecture, just...   
1  This is a representation of your brain, and yo...   
2  It's a great honor today to share with you The...   
3  My passions are music, technology and making t...   
4  It used to be that if you wanted to get a comp...   

                                                 url  
0  https://www.ted.com/talks/al_seckel_says_our_b...  
1  https://www.ted.com/talks/aaron_o_connell_maki...  
2  https://www.ted.com/talks/carter_emmart_demos_...  
3  https://www.ted.com/talks/jared_ficklin_new_wa...  
4  https://www.ted.com/talks/jeremy_howard_the_wo...

Recommendations for talk at URL: https://www.ted.com/talks/al_seckel_says_our_brains_are_mis_wired

65     https://www.ted.com/talks/kary_mullis_on_what_...
456    https://www.ted.com/talks/gregory_stock_to_upg...
97     https://www.ted.com/talks/dan_ariely_asks_are_...
223    https://www.ted.com/talks/ricardo_semler_how_t...
104    https://www.ted.com/talks/rob_legato_the_art_o...
323    https://www.ted.com/talks/nic_marks_the_happy_...
153    https://www.ted.com/talks/scott_dinsmore_how_t...
57     https://www.ted.com/talks/alison_jackson_looks...
432    https://www.ted.com/talks/paola_antonelli_prev...
120    https://www.ted.com/talks/vik_muniz_makes_art_...
Name: url, dtype: object


### Beyond n-grams: word embeddings

In [ ]:
sent = "I like apples and oranges"

# Create the doc object
doc = nlp(sent)

# Compute pairwise similarity scores
for token1 in doc:
  for token2 in doc:
    print(token1.text, token2.text, token1.similarity(token2))


# Good job! Notice how the words 'apples' and 'oranges' have the highest pairwaise similarity score.
# This is expected as they are both fruits and are more related to each other than any other pair of words.

I I 1.0
I like 0.19823068380355835
I apples 0.16132277250289917
I and -0.04532375931739807
I oranges 0.06013873219490051
like I 0.19823068380355835
like like 1.0
like apples 0.02722913958132267
like and -0.019127340987324715
like oranges 0.017664654180407524
apples I 0.16132277250289917
apples like 0.02722913958132267
apples apples 1.0
apples and -0.00598952965810895
apples oranges 0.39695537090301514
and I -0.04532375931739807
and like -0.019127340987324715
and apples -0.00598952965810895
and and 1.0
and oranges -0.005365171004086733
oranges I 0.06013873219490051
oranges like 0.017664654180407524
oranges apples 0.39695537090301514
oranges and -0.005365171004086733
oranges oranges 1.0


/tmp/ipython-input-40-825226101.py:9: UserWarning: [W007] The model you're using has no word vectors loaded, so the result of the Token.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only use context-sensitive tensors. You can always add your own word vectors, or use one of the larger models instead if available.
  print(token1.text, token2.text, token1.similarity(token2))


**Computing similarity of Pink Floyd songs**  
In this final exercise, you have been given lyrics of three songs by the British band Pink Floyd, namely 'High Hopes', 'Hey You' and 'Mother'. The lyrics to these songs are available as hopes, hey and mother respectively.

Your task is to compute the pairwise similarity between mother and hopes, and mother and hey.



In [ ]:
mother = "\nMother do you think they'll drop the bomb?\nMother do you think they'll like this song?\nMother do you think they'll try to break my balls?\nOoh, ah\nMother should I build the wall?\nMother should I run for President?\nMother should I trust the government?\nMother will they put me in the firing mine?\nOoh ah,\nIs it just a waste of time?\nHush now baby, baby, don't you cry.\nMama's gonna make all your nightmares come true.\nMama's gonna put all her fears into you.\nMama's gonna keep you right here under her wing.\nShe won't let you fly, but she might let you sing.\nMama's gonna keep baby cozy and warm.\nOoh baby, ooh baby, ooh baby,\nOf course mama's gonna help build the wall.\nMother do you think she's good enough, for me?\nMother do you think she's dangerous, to me?\nMother will she tear your little boy apart?\nOoh ah,\nMother will she break my heart?\nHush now baby, baby don't you cry.\nMama's gonna check out all your girlfriends for you.\nMama won't let anyone dirty get through.\nMama's gonna wait up until you get in.\nMama will always find out where you've been.\nMama's gonna keep baby healthy and clean.\nOoh baby, ooh baby, ooh baby,\nYou'll always be baby to me.\nMother, did it need to be so high?\n"
hopes = "\nBeyond the horizon of the place we lived when we were young\nIn a world of magnets and miracles\nOur thoughts strayed constantly and without boundary\nThe ringing of the division bell had begun\nAlong the Long Road and on down the Causeway\nDo they still meet there by the Cut\nThere was a ragged band that followed in our footsteps\nRunning before times took our dreams away\nLeaving the myriad small creatures trying to tie us to the ground\nTo a life consumed by slow decay\nThe grass was greener\nThe light was brighter\nWhen friends surrounded\nThe nights of wonder\nLooking beyond the embers of bridges glowing behind us\nTo a glimpse of how green it was on the other side\nSteps taken forwards but sleepwalking back again\nDragged by the force of some in a tide\nAt a higher altitude with flag unfurled\nWe reached the dizzy heights of that dreamed of world\nEncumbered forever by desire and ambition\nThere's a hunger still unsatisfied\nOur weary eyes still stray to the horizon\nThough down this road we've been so many times\nThe grass was greener\nThe light was brighter\nThe taste was sweeter\nThe nights of wonder\nWith friends surrounded\nThe dawn mist glowing\nThe water flowing\nThe endless river\nForever and ever\n"
hey = "\nHey you, out there in the cold\nGetting lonely, getting old\nCan you feel me?\nHey you, standing in the aisles\nWith itchy feet and fading smiles\nCan you feel me?\nHey you, don't help them to bury the light\nDon't give in without a fight\nHey you out there on your own\nSitting naked by the phone\nWould you touch me?\nHey you with you ear against the wall\nWaiting for someone to call out\nWould you touch me?\nHey you, would you help me to carry the stone?\nOpen your heart, I'm coming home\nBut it was only fantasy\nThe wall was too high\nAs you can see\nNo matter how he tried\nHe could not break free\nAnd the worms ate into his brain\nHey you, out there on the road\nAlways doing what you're told\nCan you help me?\nHey you, out there beyond the wall\nBreaking bottles in the hall\nCan you help me?\nHey you, don't tell me there's no hope at all\nTogether we stand, divided we fall\n"


# Create Doc objects
mother_doc = nlp(mother)
hopes_doc = nlp(hopes)
hey_doc = nlp(hey)

# Print similarity between mother and hopes
print(mother_doc.similarity(hopes_doc))
# Print similarity between mother and hey
print(mother_doc.similarity(hey_doc))

# Notice that 'Mother' and 'Hey You' have a similarity score of 0.9 whereas 'Mother' and 'High Hopes' has a score of only 0.6.
# This is probably because 'Mother' and 'Hey You' were both songs from the same album 'The Wall' and were penned by Roger Waters.
# On the other hand, 'High Hopes' was a part of the album 'Division Bell' with lyrics by David Gilmour and his wife, Penny Samson.
# Treat yourself by listening to these songs. They're some of the best!

0.36541473865509033
0.7763113975524902


/tmp/ipython-input-42-2896140850.py:12: UserWarning: [W007] The model you're using has no word vectors loaded, so the result of the Doc.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only use context-sensitive tensors. You can always add your own word vectors, or use one of the larger models instead if available.
  print(mother_doc.similarity(hopes_doc))
/tmp/ipython-input-42-2896140850.py:14: UserWarning: [W007] The model you're using has no word vectors loaded, so the result of the Doc.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only use context-sensitive tensors. You can always add your own word vectors, or use one of 